export const FETCH_RECOMMENDED_LOADING = "FETCH_RECOMMENDED_LOADING";
export const FETCH_RECOMMENDED_SUCCESS = "FETCH_RECOMMENDED_SUCCESS";
export const FETCH_RECOMMENDED_ERROR = "FETCH_RECOMMENDED_ERROR";