export const FETCH_MOVIE_LOADING = "FETCH_MOVIE_LOADING";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";



export const FETCH_MOVIE_DIRECTORS_LOADING = "FETCH_MOVIE_DIRECTORS_LOADING";
export const FETCH_MOVIE_DIRECTORS_SUCCESS = "FETCH_MOVIE_DIRECTORS_SUCCESS";
export const FETCH_MOVIE_DIRECTORS_ERROR = "FETCH_MOVIE_DIRECTORS_ERROR";